version: '3.7'
services:
  build-env:
    container_name: build-env
    image: edgeda:build-env
    build:
      context: .
      target: build-env
  zpub: 
    container_name: zpub
    image: edgeda:zpub
    environment:
      - PORT=${PUBPI_PORT}
    build:
      context: .
      target: zpub
    networks: 
      - pubpi
  zpi: 
    container_name: zpi
    image: edgeda:zpi
    environment:
      - PORT_IN=${PUBPI_PORT}
      - PORT_OUT=${PISUB_PORT}
    build:
      context: .
      target: zpi
    networks:
      - pubpi
      - pisub
  zsub: 
    container_name: zsub
    image: edgeda:zsub
    environment:
      - PORT=${PISUB_PORT}
    build:
      context: .
      target: zsub
    networks:
      - pisub

networks:
  pubpi:
    name: pub-to-pi
    driver: bridge
  pisub:
    name: pi-to-sub
    driver: bridge
